bisecting cause commit starting from edeca3a769ad28a9477798c3b1d8e0701db728e4
building syzkaller on 87815d9d3240b653160e1eb4e5a6931c0c3bd0d9
testing commit edeca3a769ad28a9477798c3b1d8e0701db728e4 with gcc (GCC) 8.1.0
run #0: crashed: BUG: corrupted list in p9_read_work
run #1: crashed: BUG: corrupted list in p9_read_work
run #2: crashed: BUG: corrupted list in p9_read_work
run #3: crashed: no output from test machine
run #4: crashed: no output from test machine
run #5: crashed: no output from test machine
run #6: crashed: no output from test machine
run #7: crashed: no output from test machine
run #8: crashed: no output from test machine
run #9: crashed: no output from test machine
testing release v4.19
testing commit 84df9525b0c27f3ebc2ebb1864fa62a97fdedb7d with gcc (GCC) 8.1.0
run #0: crashed: BUG: corrupted list in p9_read_work
run #1: crashed: BUG: corrupted list in p9_read_work
run #2: crashed: BUG: corrupted list in p9_read_work
run #3: crashed: BUG: corrupted list in p9_read_work
run #4: crashed: BUG: corrupted list in p9_read_work
run #5: crashed: BUG: corrupted list in p9_read_work
run #6: OK
run #7: crashed: no output from test machine
run #8: crashed: no output from test machine
run #9: crashed: no output from test machine
testing release v4.18
testing commit 94710cac0ef4ee177a63b5227664b38c95bbf703 with gcc (GCC) 8.1.0
run #0: crashed: KASAN: use-after-free Read in p9_poll_workfn
run #1: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #2: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #3: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #4: crashed: KASAN: use-after-free Read in p9_poll_workfn
run #5: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #6: crashed: KASAN: use-after-free Read in p9_poll_workfn
run #7: crashed: KASAN: use-after-free Read in p9_poll_workfn
run #8: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #9: crashed: KASAN: use-after-free Read in p9_conn_cancel
testing release v4.17
testing commit 29dcea88779c856c7dc92040a0c01233263101d4 with gcc (GCC) 8.1.0
run #0: crashed: BUG: unable to handle kernel NULL pointer dereference in kfree
run #1: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #2: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #3: crashed: KASAN: use-after-free Read in p9_poll_workfn
run #4: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #5: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #6: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #7: crashed: KASAN: use-after-free Read in __queue_work
run #8: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #9: crashed: KASAN: use-after-free Read in p9_conn_cancel
testing release v4.16
testing commit 0adb32858b0bddf4ada5f364a84ed60b196dbcda with gcc (GCC) 8.1.0
run #0: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #1: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #2: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #3: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #4: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #5: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #6: crashed: KASAN: use-after-free Read in __queue_work
run #7: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #8: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #9: crashed: KASAN: use-after-free Read in p9_conn_cancel
testing release v4.15
testing commit d8a5b80568a9cb66810e75b182018e9edb68e8ff with gcc (GCC) 8.1.0
all runs: crashed: KASAN: use-after-free Read in p9_conn_cancel
testing release v4.14
testing commit bebc6082da0a9f5d47a1ea2edc099bf671058bd4 with gcc (GCC) 8.1.0
run #0: crashed: BUG: corrupted list in p9_conn_cancel
run #1: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #2: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #3: crashed: INFO: task hung in flush_work
run #4: crashed: INFO: task hung in flush_work
run #5: crashed: INFO: task hung in flush_work
run #6: crashed: INFO: task hung in flush_work
run #7: crashed: INFO: task hung in flush_work
run #8: crashed: INFO: task hung in flush_work
run #9: crashed: INFO: task hung in flush_work
testing release v4.13
testing commit 569dbb88e80deb68974ef6fdd6a13edb9d686261 with gcc (GCC) 8.1.0
run #0: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #1: crashed: INFO: task hung in flush_work
run #2: crashed: INFO: task hung in flush_work
run #3: crashed: INFO: task hung in flush_work
run #4: crashed: INFO: task hung in flush_work
run #5: crashed: INFO: task hung in flush_work
run #6: crashed: INFO: task hung in flush_work
run #7: crashed: INFO: task hung in flush_work
run #8: crashed: INFO: task hung in flush_work
run #9: crashed: no output from test machine
testing release v4.12
testing commit 6f7da290413ba713f0cdd9ff1a2a9bb129ef4f6c with gcc (GCC) 8.1.0
run #0: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #1: OK
run #2: OK
run #3: OK
run #4: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #5: crashed: no output from test machine
run #6: crashed: no output from test machine
run #7: crashed: no output from test machine
run #8: crashed: no output from test machine
run #9: crashed: no output from test machine
testing release v4.11
testing commit a351e9b9fc24e982ec2f0e76379a49826036da12 with gcc (GCC) 7.3.0
run #0: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #1: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #2: crashed: no output from test machine
run #3: crashed: no output from test machine
run #4: crashed: no output from test machine
run #5: crashed: no output from test machine
run #6: crashed: no output from test machine
run #7: crashed: no output from test machine
run #8: crashed: no output from test machine
run #9: crashed: no output from test machine
testing release v4.10
testing commit c470abd4fde40ea6a0846a2beab642a578c0b8cd with gcc (GCC) 5.5.0
run #0: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #1: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #2: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #3: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #4: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #5: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #6: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #7: crashed: no output from test machine
run #8: crashed: no output from test machine
run #9: crashed: no output from test machine
testing release v4.9
testing commit 69973b830859bc6529a7a0468ba0d80ee5117826 with gcc (GCC) 5.5.0
run #0: crashed: KASAN: slab-out-of-bounds Read in p9pdu_readf
run #1: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #2: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #3: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #4: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #5: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #6: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #7: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #8: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #9: crashed: KASAN: use-after-free Read in p9_conn_cancel
testing release v4.8
testing commit c8d2bc9bc39ebea8437fd974fdbc21847bb897a3 with gcc (GCC) 5.5.0
run #0: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #1: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #2: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #3: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #4: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #5: crashed: WARNING in __list_del_entry
run #6: OK
run #7: crashed: no output from test machine
run #8: OK
run #9: OK
testing release v4.7
testing commit 523d939ef98fd712632d93a5a2b588e477a7565e with gcc (GCC) 5.5.0
run #0: OK
run #1: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #2: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #3: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #4: crashed: WARNING in __list_del_entry
run #5: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #6: crashed: no output from test machine
run #7: crashed: no output from test machine
run #8: OK
run #9: OK
testing release v4.6
testing commit 2dcd0af568b0cf583645c8a317dd12e344b1c72a with gcc (GCC) 5.5.0
run #0: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #1: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #2: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #3: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #4: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #5: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #6: crashed: KASAN: use-after-free Read in p9_conn_cancel
run #7: OK
run #8: OK
run #9: crashed: no output from test machine
testing release v4.5
testing commit b562e44f507e863c6792946e4e1b1449fbbac85d with gcc (GCC) 5.5.0
run #0: crashed: WARNING in __list_del_entry
run #1: crashed: WARNING in __list_del_entry
run #2: OK
run #3: crashed: WARNING in __list_del_entry
run #4: crashed: no output from test machine
run #5: OK
run #6: OK
run #7: OK
run #8: OK
run #9: OK
testing release v4.4
testing commit afd2ff9b7e1b367172f18ba7f693dfb62bdcb2dc with gcc (GCC) 5.5.0
run #0: crashed: WARNING in __list_del_entry
run #1: crashed: WARNING in work_fixup_activate
run #2: crashed: WARNING in __list_del_entry
run #3: crashed: WARNING in __list_del_entry
run #4: crashed: no output from test machine
run #5: crashed: WARNING in __list_del_entry
run #6: OK
run #7: OK
run #8: OK
run #9: OK
testing release v4.3
testing commit 6a13feb9c82803e2b815eca72fa7a9f5561d7861 with gcc (GCC) 5.5.0
run #0: crashed: WARNING in work_fixup_activate
run #1: crashed: WARNING in __list_del_entry
run #2: crashed: general protection fault in p9_fd_poll
run #3: crashed: BUG: unable to handle kernel
run #4: crashed: WARNING: ODEBUG bug in p9_fd_close
run #5: crashed: BUG: unable to handle kernel NULL pointer dereference in p9_conn_cancel
run #6: crashed: WARNING in __list_del_entry
run #7: crashed: BUG: unable to handle kernel
run #8: OK
run #9: OK
testing release v4.2
testing commit 64291f7db5bd8150a74ad2036f1037e6a0428df2 with gcc (GCC) 5.5.0
run #0: crashed: BUG: unable to handle kernel
run #1: crashed: WARNING in __list_del_entry
run #2: crashed: general protection fault in ext4_htree_store_dirent
run #3: crashed: WARNING in work_fixup_activate
run #4: crashed: no output from test machine
run #5: OK
run #6: OK
run #7: OK
run #8: OK
run #9: OK
testing release v4.1
testing commit b953c0d234bc72e8489d3bf51a276c5c4ec85345 with gcc (GCC) 5.5.0
run #0: crashed: WARNING in __list_del_entry
run #1: crashed: general protection fault in p9_fd_poll
run #2: crashed: WARNING in __list_del_entry
run #3: crashed: WARNING in __list_del_entry
run #4: crashed: WARNING in __list_del_entry
run #5: crashed: WARNING in __list_del_entry
run #6: crashed: no output from test machine
run #7: OK
run #8: OK
run #9: OK
revisions tested: 20, total time: 3h53m58.593508658s (build: 1h23m22.539036469s, test: 2h26m10.449522372s)
the crash already happened on the oldest tested release
crash: no output from test machine

